{ pkgs, ... }:

{
  name = "loft-integration";

  nodes = {
    machine = { config, pkgs, lib, ... }: {
      imports = [ ../module.nix ];

      virtualisation.diskSize = 2048;
      virtualisation.memorySize = 2048;
      virtualisation.cores = 2;

      environment.systemPackages = with pkgs; [
        garage
        awscli2
        jq
        nix
      ];

      nix.settings = {
        experimental-features = [ "nix-command" "flakes" ];
        substituters = lib.mkForce [];
      };

      # Use the nixpkgs from the test runner
      nix.nixPath = [ "nixpkgs=${pkgs.path}" ];

      services.garage = {
        enable = true;
        package = pkgs.garage;
        settings = {
          metadata_dir = "/var/lib/garage/meta";
          data_dir = "/var/lib/garage/data";
          db_engine = "sqlite";
          replication_factor = 1;
          rpc_bind_addr = "[::]:3901";
          rpc_public_addr = "127.0.0.1:3901";
          s3_api = {
            s3_region = "us-east-1";
            api_bind_addr = "[::]:3900";
            root_domain = ".s3.garage.localhost";
          };
          admin = {
            api_bind_addr = "[::]:3903";
          };
        };
      };

      services.loft = {
        enable = true;
        s3 = {
          bucket = "loft-test-bucket";
          endpoint = "http://localhost:3900";
          accessKeyFile = "/tmp/access-key";
          secretKeyFile = "/tmp/secret-key";
        };
        scanOnStartup = true;
        uploadThreads = 2;
      };

      # Disable auto-start so we can provision keys first
      systemd.services.loft.wantedBy = lib.mkForce [];
    };
  };

  testScript = ''
    start_all()

    # 1. Setup Garage
    machine.wait_for_unit("garage.service")
    machine.wait_for_open_port(3900)
    machine.wait_for_open_port(3903)

    # Configure Garage (layout)
    # New garage versions need layout assignment
    machine.succeed("garage layout assign -z 1 -c 1 -t 0")
    machine.succeed("garage layout apply --version 1")

    # Create key
    # Garage key create output is user-friendly, we need to parse it or use JSON output if available.
    # `garage key create` doesn't seem to support JSON output in all versions.
    # Let's use grep/awk.

    machine.succeed("garage key create test-key")

    # Extract keys
    # garage key list --show-secret outputs a table.
    # ID                                    Name      Secret key
    # GK...                                 test-key  ...

    access_key = machine.succeed("garage key list --show-secret | grep test-key | awk '{print $1}'").strip()
    secret_key = machine.succeed("garage key list --show-secret | grep test-key | awk '{print $3}'").strip()

    machine.succeed(f"echo -n '{access_key}' > /tmp/access-key")
    machine.succeed(f"echo -n '{secret_key}' > /tmp/secret-key")

    print(f"Access Key: {access_key}")

    # Create bucket
    machine.succeed(f"AWS_ACCESS_KEY_ID={access_key} AWS_SECRET_ACCESS_KEY={secret_key} aws --endpoint-url http://localhost:3900 s3 mb s3://loft-test-bucket")

    # 2. Start Loft
    machine.systemctl("start loft.service")
    machine.wait_for_unit("loft.service")

    # Check logs to ensure it started correctly
    machine.succeed("journalctl -u loft.service --grep 'Starting scan of existing store paths'")

    # 3. Create Data (Basic Upload)
    # We use a simple runCommand to generate a store path
    # We need to make sure the path is NOT already in the store (it shouldn't be, it's a fresh VM)
    # But nixpkgs is in the store.

    out_path = machine.succeed("nix-build -E '(import <nixpkgs> {}).runCommand \"test-pkg\" {} \"echo hello > $out\"'").strip()
    print(f"Created path: {out_path}")

    # Loft should pick it up via the watcher.
    # Wait for upload to complete.
    # We can check logs for "Successfully uploaded path".

    machine.wait_until_succeeds(f"journalctl -u loft.service --grep 'Successfully uploaded .narinfo for {out_path}'")

    # Verify in S3
    # We need to calculate the hash to find the object?
    # Or just list the bucket.
    s3_ls = machine.succeed(f"AWS_ACCESS_KEY_ID={access_key} AWS_SECRET_ACCESS_KEY={secret_key} aws --endpoint-url http://localhost:3900 s3 ls s3://loft-test-bucket/ --recursive")
    print(s3_ls)
    if "narinfo" not in s3_ls:
        raise Exception("No narinfo found in S3")

    # 4. Deduplication
    # Trigger a manual upload of the same path?
    # The `loft` binary has a CLI interface.
    # Usage: loft --config ... --upload-path ...
    # We need to locate the config file generated by the module.
    # The module generates it in the store, but we don't know the path easily.
    # However, the service wrapper uses `config.systemd.services.loft.serviceConfig.ExecStart`.
    # We can check the process arguments.

    # Alternatively, we can just rely on the fact that if we restart Loft, it scans again.

    machine.systemctl("restart loft.service")
    machine.wait_for_unit("loft.service")

    # Check logs for "skipping" or similar if we implemented that logging.
    # Or check that S3 timestamp didn't change (harder to verify).

    # 5. Service Resilience
    machine.systemctl("stop loft.service")

    # Create another path
    out_path_2 = machine.succeed("nix-build -E '(import <nixpkgs> {}).runCommand \"test-pkg-2\" {} \"echo world > $out\"'").strip()
    print(f"Created path 2: {out_path_2}")

    machine.systemctl("start loft.service")
    machine.wait_for_unit("loft.service")

    # It should be picked up by the initial scan.
    machine.wait_until_succeeds(f"journalctl -u loft.service --grep 'Successfully uploaded .narinfo for {out_path_2}'")

    # Verify in S3
    s3_ls_2 = machine.succeed(f"AWS_ACCESS_KEY_ID={access_key} AWS_SECRET_ACCESS_KEY={secret_key} aws --endpoint-url http://localhost:3900 s3 ls s3://loft-test-bucket/ --recursive")
    print(s3_ls_2)
    # Check that we have more files now

  '';
}
