name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Adjust AppArmor Profile for Bubblewrap
        # https://github.com/actions/runner-images/issues/9491#issuecomment-1989718917
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Run checks
        run: nix flake check -L
